image: nixos/nix:2.19.3-amd64

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  stage: deploy
  scripts:
    - echo 'Nothing to do'
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  artifacts:
    paths:
      - public/
