name: Deploy static content to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Setup bunjs
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build static site
        run: bun run build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
